- name: Ensure destination bin dir exists
  file:
    path: "{{ scw_sd_bin_dir }}"
    state: directory
    mode: '0755'

- name: Download scw-sd binary
  get_url:
    url: "{{ scw_sd_download_url }}"
    dest: "{{ scw_sd_bin_dir }}/scw-sd"
    mode: '0755'
  notify: Restart scw-sd

- name: Deploy systemd unit
  template:
    src: scw-sd.service.j2
    dest: /etc/systemd/system/scw-sd.service
    mode: '0644'
  notify: Reload systemd

- name: Enable and start scw-sd service
  systemd:
    name: scw-sd
    enabled: true
    state: started
